// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvcgfnnhykfxlsryrqii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52Y2dmbm5oeWtmeGxzcnlycWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzkzNjUsImV4cCI6MjA3MDExNTM2NX0.zbzB2cFQXN-XGAvNAeKp1kTr3ohT5ZsoOx2KMOukbcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});